//Defining macros
#define SIZE 10
#define BUFFER_SIZE 20
#define TOTALSEATS 32
#define BOOKEDSEATS 0
#define FARE 0.0
#define EXIT_SUCCESS 0
#define TRUE 1
#define FALSE 0
#define ADMIN 1
#define USER 2
#define EXIT 3
#define ADDBUS 1
#define VIEWBUS 2
#define EDITBUS 3
#define DELETEBUS 4
#define SHOWALLBUS 5
#define BOOKINGSMENU 6
#define BACK 7
#define LOGIN 1
#define REGISTER 2
#define PREVIOUS 3
#define BOOKTICKET 1
#define VIEWTICKET 2
#define EDITTICKET 3
#define CANCELTICKET 4
#define GOBACK 5
#define TICKETBYPNR 1
#define TICKETBYNAME 2
#define TICKETBYBUS 3
#define TICKETBYSOURCE 4
#define TICKETBYDESTINATION 5
#define MENU 6
#define USERNAME "group3"
#define PASSWORD "Capg@123"